### ISSUE TITLE
Percent sign in grammar breaks "Save BNF as URL"

### ISSUE THREAD

**Issue by mikesamuel** [paul-kline/bnf-playground#2]
Enter the following in the Editor tab's grammar input box

```bnf
<Percent> ::= "%"
```

hit <kbd>Save BNF as URL</kbd> and I get the URL

    https://bnfplayground.pauliankline.com/?bnf=%3CPercent%3E%20%3A%3A%3D%20%22%25%22&name=
    
Opening that in the browser (recent Chrome) and looking at the JS console I see

> ```
> URIError: URI malformed
>     at decodeURIComponent (<anonymous>)
>     at f.value (f80ab1d.js:1)
>     at f.value (f80ab1d.js:1)
>     at Qt (c4c8d66.js:2)
>     at cn (c4c8d66.js:2)
>     at Object.insert (c4c8d66.js:2)
>     at j (c4c8d66.js:2)
>     at jn.__patch__ (c4c8d66.js:2)
>     at jn.t._update (c4c8d66.js:2)
>     at jn.r (c4c8d66.js:2)
> ```

but this problem does not manifest for

```bnf
<Dot> ::= "."
```

**Comment by mikesamuel** [comment]
Relevant code seems to be

https://github.com/paul-kline/bnf-playground/blob/7e0155dc9a3aa92f507be27a6d04f663bc504e85/components/editor.vue#L128-L158

**Comment by mikesamuel** [comment]
I think `url.searchParams.get` decodes.

The last line of the note at https://url.spec.whatwg.org/#example-constructing-urlsearchparams suggests that

> ```js
> const url = new URL('https://example.com/?a=~&b=%7E');
> console.log(url.search);                // "?a=~&b=%7E"
> console.log(url.searchParams.get('a')); // "~"
> console.log(url.searchParams.get('b')); // "~"
> ```

**Comment by paul-kline** [comment]
thanks for the fix. #3
