### ISSUE TITLE
How to specify an optional syntax ?

### ISSUE THREAD

**Issue by springcomp** [paul-kline/bnf-playground#5]
I’m trying to create the following token, expressed as ABNF syntax:

```abnf
number            = ["-"] 1*digit
```

The best I could come up with in the BNF Playground is this:

```ebnf
<number> ::= <digit>+ | "-" <digit>+
```

How would it be possible to express the `"-"` minus sign as being optional (_i.e_ appearing exactly zero, or one time) ?

**Comment by paul-kline** [comment]
You can do exactly that, but you have to use ebnf syntax as specified in the grammar help section:
https://bnfplayground.pauliankline.com/

`<number> ::= <digit>+ | "-"? <digit>+`

**Comment by springcomp** [comment]
Oh, I missed that. Thanks a lot.
