### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rbtylee** [paul-kline/bnf-playground#9]
I am unsure what license this code has. I am asking because I may create a repo with some BNFs of interest to me that work on the web-site and would like to include the grammar help, the markdown found in the file grammarhelp.vue in the repo's readme. The BNFs and EBNFs accepted by your code varies a little from various documents I have read on BNFs. Your grammar helps clarify some of that. A license file would clarify whether I would be allowed to use that text. Naturally, you saying yes or no to using in response to this issue would be just as good.

Thanks for the work on this project, this is a great app and much-needed online.

**Comment by paul-kline** [comment]
No problem. Feel free to use it. A while back someone from Mozilla
contacted me about making the source code available so I did.

**Comment by rbtylee** [comment]
Thanks :) It's up to you whether you wish to choose and commit a license. At some point when I find time I will look over your code but web dev stuff like this is a little out of my comfort zone. I will consider this issue closed for now.
